targets:
  $default:
    sources:
      - "node/**"
      - "lib/**"
      - "$package$"
    builders:
      build_node_compilers|entrypoint:
        generate_for:
        - node/**
        options:
          compiler: dart2js
          # List any dart2js specific args here, or omit it.
          dart2js_args:
          - -DSTAGING_BRANCH=ci-test-data
          # - --minify
